backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

locale: 'de'

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads


collections:
  - name: "pages"
    label: "Seiten"
    folder: "content/pages"
    files:
    - label: "Stamm"
      name: "stamm"
      file: "content/pages/stamm/index.md"
      fields:
        - {label: "Titel", name: "title", widget: "string"}
        - {label: "Untertitel", name: "subtitle", widget: "string", required: false}
        - {label: "Datum", name: "date", widget: "datetime"}
        - {label: "Foto", name: "thumbnail", widget: "image", required: false}
        - label: "Bilder"
          name: "images"
          widget: "list"
          summary: '{{fields.image}}'
          field: {label: Image, name: image, widget: image}
          required: false
        - {label: "Inhalt", name: "body", widget: "markdown", required: false}
    - label: "Stammesheim"
      name: "stammesheim"
      file: "content/pages/stammesheim/index.md"
      fields:
        - {label: "Titel", name: "title", widget: "string"}
        - {label: "Untertitel", name: "subtitle", widget: "string", required: false}
        - {label: "Datum", name: "date", widget: "datetime"}
        - {label: "Foto", name: "thumbnail", widget: "image", required: false}
        - label: "Bilder"
          name: "images"
          widget: "list"
          summary: '{{fields.image}}'
          field: {label: Image, name: image, widget: image}
          required: false
        - {label: "Inhalt", name: "body", widget: "markdown", required: false}
    - label: "Stammesführung"
      name: "stammesfuehrung"
      file: "content/pages/stammesfuehrung/index.md"
      fields:
        - {label: "Titel", name: "title", widget: "string"}
        - {label: "Untertitel", name: "subtitle", widget: "string", required: false}
        - {label: "Datum", name: "date", widget: "datetime"}
        - {label: "Foto", name: "thumbnail", widget: "image", required: false}
        - label: "Bilder"
          name: "images"
          widget: "list"
          summary: '{{fields.image}}'
          field: {label: Image, name: image, widget: image}
          required: false
        - {label: "Inhalt", name: "body", widget: "markdown", required: false}
    - label: "Freundeskreis"
      name: "freundeskreis"
      file: "content/pages/freundeskreis/index.md"
      fields:
        - {label: "Titel", name: "title", widget: "string"}
        - {label: "Untertitel", name: "subtitle", widget: "string", required: false}
        - {label: "Datum", name: "date", widget: "datetime"}
        - {label: "Foto", name: "thumbnail", widget: "image", required: false}
        - label: "Bilder"
          name: "images"
          widget: "list"
          summary: '{{fields.image}}'
          field: {label: Image, name: image, widget: image}
          required: false
        - {label: "Inhalt", name: "body", widget: "markdown", required: false}
  - name: "gruppen"
    label: "Gruppen"
    folder: "content/gruppen"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Untertitel", name: "subtitle", widget: "string", required: false}
      - {label: "Datum", name: "date", widget: "datetime"}

      - {label: "Gewichtung (UI)", name: "weight", widget: "number", default: "1"}
      - {label: "Icon", name: "icon", widget: "image"}

      - {label: "Gruppenstunde", name: "meets", widget: "string", default: "unregelmäßig"}
      - {label: "Jahrgänge", name: "years", widget: "string", default: "noch unbekannt"}
      - {label: "Gruppenleitung", name: "leaders", widget: "string", default: "noch unbekannt"}
      - {label: "Kontakt", name: "contact", widget: "string"}

      - {label: "Foto", name: "thumbnail", widget: "image", required: false}
      - label: "Bilder"
        name: "images"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
        required: false
      - {label: "Inhalt", name: "body", widget: "markdown", required: false}
  - name: "lager"
    label: "Lager"
    folder: "content/lager"
    slug: "{{year}}-{{slug}}"
    create: true
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Untertitel", name: "subtitle", widget: "string", required: false}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Foto", name: "thumbnail", widget: "image", required: false}
      - label: "Bilder"
        name: "images"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
        required: false
      - {label: "Inhalt", name: "body", widget: "markdown", required: false}
