backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

locale: 'de'

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads


collections:
  - name: "gruppen"
    label: "Gruppen"
    folder: "content/gruppen"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Untertitel", name: "subtitle", widget: "string", required: false}
      - {label: "Datum", name: "date", widget: "datetime"}

      - {label: "Gruppenstunde", name: "meets", widget: "string", required: false}
      - {label: "Jahrgänge", name: "years", widget: "string", required: false}
      - {label: "Gruppenleitung", name: "leaders", widget: "string", required: false}
      - {label: "Kontakt", name: "contact", widget: "string", required: false}

      - {label: "Foto", name: "thumbnail", widget: "image", required: false}
      - label: "Bilder"
        name: "images"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
        required: false
      - {label: "Inhalt", name: "body", widget: "markdown", required: false}
  - name: "lager"
    label: "Lager"
    folder: "content/lager"
    slug: "{{year}}-{{slug}}"
    create: true
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Untertitel", name: "subtitle", widget: "string", required: false}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Foto", name: "thumbnail", widget: "image", required: false}
      - label: "Bilder"
        name: "images"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
        required: false
      - {label: "Inhalt", name: "body", widget: "markdown", required: false}
