backend:
  name: github
  repo: stamm-barrakuda/barrakuda-de
  branch: main
  base_url: https://decap-oauth.jzbor.de

locale: 'de'

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads


collections:
  - name: "gruppen"
    label: "Gruppen"
    folder: "content/gruppen"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Untertitel", name: "subtitle", widget: "string", required: false}
      - {label: "Datum", name: "date", widget: "datetime"}

      - {label: "Gewichtung (UI)", name: "weight", widget: "number", default: "1"}
      - {label: "Icon", name: "icon", widget: "image"}

      - {label: "Gruppenstunde", name: "meets", widget: "string", default: "unregelmäßig"}
      - {label: "Jahrgänge", name: "years", widget: "string", default: "noch unbekannt"}
      - {label: "Gruppenleitung", name: "leaders", widget: "string", default: "noch unbekannt"}
      - {label: "Kontakt", name: "contact", widget: "string"}

      - {label: "Foto", name: "thumbnail", widget: "image", required: false}
      - label: "Bilder"
        name: "images"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
        required: false
      - {label: "Inhalt", name: "body", widget: "markdown", required: false}
  - name: "lager"
    label: "Lager"
    folder: "content/lager"
    slug: "{{year}}-{{slug}}"
    create: true
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Untertitel", name: "subtitle", widget: "string", required: false}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Entwurf", name: "draft", widget: "boolean", default: false, required: false}
      - {label: "Foto", name: "thumbnail", widget: "image", required: false}
      - label: "Bilder"
        name: "images"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
        required: false
      - {label: "Inhalt", name: "body", widget: "markdown", required: false}
  - name: "stamm"
    label: "Stamm"
    folder: "content/pages/stamm"
    create: false
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Untertitel", name: "subtitle", widget: "string", required: false}
      - {label: "Datum", name: "date", widget: "datetime"}
      # - {label: "Foto", name: "thumbnail", widget: "image", required: false}
      - {label: "Inhalt", name: "body", widget: "markdown", required: false}
  - name: "stammesheim"
    label: "Stammesheim"
    folder: "content/pages/stammesheim"
    create: false
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Untertitel", name: "subtitle", widget: "string", required: false}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Foto", name: "thumbnail", widget: "image", required: false}
      - {label: "Inhalt", name: "body", widget: "markdown", required: false}
  - name: "stammesefuehrung"
    label: "Stammesführung"
    folder: "content/pages/stammesfuehrung"
    create: false
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Untertitel", name: "subtitle", widget: "string", required: false}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Foto", name: "thumbnail", widget: "image", required: false}
      - {label: "Inhalt", name: "body", widget: "markdown", required: false}
  - name: "freundeskreis"
    label: "Freundeskreis"
    folder: "content/pages/freundeskreis"
    create: false
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Untertitel", name: "subtitle", widget: "string", required: false}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Foto", name: "thumbnail", widget: "image", required: false}
      - {label: "Inhalt", name: "body", widget: "markdown", required: false}
  - name: "jubilaeum"
    label: "Jubiläum"
    folder: "content/pages/jubilaeum"
    create: false
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Untertitel", name: "subtitle", widget: "string", required: false}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Foto", name: "thumbnail", widget: "image", required: false}
      - {label: "Inhalt", name: "body", widget: "markdown", required: false}
