backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

locale: 'de'

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads


collections:
  - name: "lager"
    label: "Lager"
    folder: "content/lager"
    slug: "{{year}}-{{slug}}"
    create: true
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Nochmal Titel", name: "heroHeading", widget: "string"}
      - {label: "Untertitel", name: "heroSubHeading", widget: "string", required: false}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Foto", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
